# This is a basic workflow to help you get started with Actions

name: Run Nox

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_all_tests:
    name: Run nox
    runs-on: ubuntu-latest
    steps:
      # (other steps before this: checkout code, install python and nox...)
      - uses: actions/checkout@v2
      - uses: wntrblm/nox@2022.1.7
      - run: nox
