# This is a basic workflow to help you get started with Actions

name: Run Nox

on:
  pull_request:
  workflow_dispatch:

jobs:
  run_all_tests:
    name: Run nox
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup nox
        uses: excitedleigh/setup-nox@main
      - name: run nox
        run: nox
      - name: upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ///home/runner/work/HABAppRules/HABAppRules/tests/htmlcov
