# This is a basic workflow to help you get started with Actions

name: Run Nox

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_all_tests:
    name: Run nox
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         submodules: recursive
     - uses: excitedleigh/setup-nox@main
     - run: nox
