name: Run Version Check

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_all_tests:
    name: Run nox
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         submodules: recursive
     - uses: excitedleigh/setup-nox@main
     - run: nox -s version_check